### ISSUE TITLE
Defer never gets called!?

### ISSUE THREAD

**Issue by harshav17** [mlilley/appledouble#1]
https://github.com/mlilley/appledouble/blob/d88959ce151a22c9bcd81a1cc1f04f9aae7bdf2f/appledouble.go#L126

**Comment by mlilley** [comment]
I don't think there's an issue here.  Defer does get called when necessary...

Note that if Open() returns an error, then Close() doesn't need to be called.

So, it's correct to place the "defer f.Close()" after the IF block (where it runs only when Open() returns success), and also ok to _not_ call f.Close() inside the IF block before the return (because "f" doesn't need to be closed when Open() doesn't succeed!).
